dataset_dir: .
model_name_or_path: ../models/Qwen/Qwen2-0.5B-Instruct
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: lora

dataset: anti_fraud_0819_train
eval_dataset: anti_fraud_0819_eval
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 4

output_dir: ../models/Qwen/Qwen2-0.5B-Instruct_fr_0819_lf
overwrite_output_dir: true
logging_steps: 10
save_steps: 10
eval_steps: 10
eval_strategy: steps
load_best_model_at_end: true

per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3
bf16: true
gradient_checkpointing: true

lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj

plot_loss: true
